trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: true
    zipAfterPublish: true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(6d415483-a70c-4647-8151-352a0dba5021)'
    appType: 'webApp'
    appName: 'bloom-effect'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'zipDeploy'